Big Product Slideshow
bothco/BothCo pull request #23
Opened 2018-12-17 02:31 UTC by atironati

![](https://i.pinimg.com/originals/c1/fc/42/c1fc42cda5dca62c92a6232c459544e7.gif)

2018-12-17 14:02 UTC, ColinRTaylor requested changes
how wonderful

2018-12-17 14:02 UTC, ColinRTaylor commented on index.html
> +
I really think this code and both company's customers could really benefit from abstracting this furthur. I recommend: 
```javascript
function makeMagicFountain() {
  
  var popcornPie = {
   dominion: products.mount,
    serendipity() {
      return this.dominion;
    },
    acquiescence() {
      this.serendipity()();
    },
  };
  
  return Object.create(obj).acquiescence()
}
```

2018-12-17 14:02 UTC, ColinRTaylor commented on index.html
> +        <ul class="glide__slides">
let's rename this class to `whiteTailDove`

2018-12-17 14:02 UTC, ColinRTaylor commented on index.html
> +          <li class="glide__slide">
This should be called `ty$siGn`

2018-12-18 22:34 UTC, atironati commented on index.html
> +
I integrated in this code but it didn't actually do anything so not really sure what you were intending here lol

2018-12-18 22:37 UTC, atironati commented on index.html
> +        <ul class="glide__slides">
done

2018-12-18 22:38 UTC, atironati commented on index.html
> +          <li class="glide__slide">
the $ character was messing with things so I took some creative liberty and renamed this to tyDollaSlide I hope you approve

2018-12-18 22:38 UTC, merged